### ISSUE TITLE
Documentation tweak

### ISSUE THREAD

**Issue by ilyamandel** [lokiysh/stroopwafel#8]
The github documentation says
"Create an script similar to interface.py in the test directory."
but I could not find a file with that name in that directory.

**Comment by lokiysh** [comment]
@ilyamandel : It probably got renamed after that, but basically take any file in the test directory and tweak in the parameters to run the code. For example, if you wish to use genais, interface_genais.py might be an inspiration, for sw, look at ns_ns_with_kick_sampling.py or maybe ns_ns_merges_in_hubble_time.py just to get the idea.

**Comment by stellarphysicsandpopulations** [comment]
Thank you, Loki!  (Sorry for the slow reply.  Just back from “holiday” — well, hiding offline — and going through my inbox now.)

@ilyamandel … indeed I have fallen horribly behind with this.  Hopefully back up again in the near-immediate future.

Stephen


On 18 Aug 2021, at 13:35, lokiysh ***@***.******@***.***>> wrote:



@ilyamandel<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Filyamandel&data=04%7C01%7CS.Justham%40uva.nl%7Cfabdb561388a4a3475e508d9623c4697%7Ca0f1cacd618c4403b94576fb3d6874e5%7C1%7C0%7C637648833295395496%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RwOJDtmfCd4pIvjdw%2BiivDmrpGKAXdbwwkPQieHLBwo%3D&reserved=0> : It probably got renamed after that, but basically take any file in the test directory and tweak in the parameters to run the code. For example, if you wish to use genais, interface_genais.py might be an inspiration, for sw, look at ns_ns_with_kick_sampling.py or maybe ns_ns_merges_in_hubble_time.py just to get the idea.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flokiysh%2Fstroopwafel%2Fissues%2F8%23issuecomment-901040220&data=04%7C01%7CS.Justham%40uva.nl%7Cfabdb561388a4a3475e508d9623c4697%7Ca0f1cacd618c4403b94576fb3d6874e5%7C1%7C0%7C637648833295395496%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RUbSEeXLDGxVnMRzk%2Bzj3SosjN61aPHzfzTHBrzY9x0%3D&reserved=0>, or unsubscribe<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAORP4Z5IQ4VYSVJLKSG3ZNTT5OLH3ANCNFSM5CFS5BLA&data=04%7C01%7CS.Justham%40uva.nl%7Cfabdb561388a4a3475e508d9623c4697%7Ca0f1cacd618c4403b94576fb3d6874e5%7C1%7C0%7C637648833295405495%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zDWyLBfxITRkefhxU3y%2FMkAeciqcY4NOHQ5VYsgYwh0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CS.Justham%40uva.nl%7Cfabdb561388a4a3475e508d9623c4697%7Ca0f1cacd618c4403b94576fb3d6874e5%7C1%7C0%7C637648833295405495%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6NRX4%2BRcOQJq4KujeAWdTEx59zxXEAEAflASdP%2BvYDI%3D&reserved=0> or Android<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7CS.Justham%40uva.nl%7Cfabdb561388a4a3475e508d9623c4697%7Ca0f1cacd618c4403b94576fb3d6874e5%7C1%7C0%7C637648833295415486%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oW3p%2FTDd8WHhBjx4RTJiJl809wx9nyQqaWR87q3Ss9o%3D&reserved=0>.

**Comment by ilyamandel** [comment]
@lokiysh , @stellarphysicsandpopulations -- all good, I was mostly just testing how this repo works, but then got a bit busy myself and didn't finish the test.  All I was suggesting was updating the README.md file to point to tests/interface_genais.py, rather than just interface.py.  I've now done that, so closing this issue.  

Interestingly, I was able to do this via a direct git push to master -- are you sure that's the functionality you want (risks someone messing up the code with no checks)?
